config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)',
      locale: Regexp.new(I18n.available_locales.map(&:to_s).join('|')) do

    resources :channels

    root 'channels#index'
  end
end

app/models/channel.rb
# == Schema Information
#
# Table name: channels
#
#  id         :bigint           not null, primary key
#  name       :string
#  home_url   :string
#  language   :string
#  slug       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  timezone   :string
#
# Indexes
#
#  index_channels_on_slug  (slug) UNIQUE
#

# Model Channel keeps the data about the channels
#
class Channel < ApplicationRecord

  has_one_attached :logo
  slug :name

  validates :name, :logo, :language, :home_url, :timezone , presence: true
  validates :name, uniqueness: true

  scope :ordered, -> { order(:name) }

end

app/controllers/channels_controller.rb
# This is the main controller to process model Channel
#
class ChannelsController < ApplicationController

  load_and_authorize_resource find_by: :slug

  # GET /channels
  def index
    respond_to do |format|
      format.html do
        @grid = initialize_grid @channels, order: :name
      end
      format.json do
        @channels = @channels.page(params[:page]) if params[:page].present?
        @channels = @channels.per(params[:per_page]) if params[:per_page].present?
      end
    end
  end

  # GET /channels/1
  def show
  end

  # GET /channels/new
  def new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  def create
    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: t('channels.was_created') }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: t('channels.was_updated') }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: t('channels.was_deleted') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  # def set_channel
  #   @channel = Channel.find(params[:id])
  # end

  # Never trust parameters from the scary internet, only allow the white list through.
  def channel_params
    list = %i[
      home_url
      language
      logo
      name
      timezone
    ]
    params.require(:channel).permit(*list)
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@channel) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    - if @channel.logo.attached?
      - title = @channel.logo.attachment.blob.filename.to_s
    = f.input :logo, as: :image_preview,
        input_html: {accept: "image/*", title: title}
    = f.input :language, collection: locales_for_select, prompt: true
    = f.input :home_url
    = f.input :timezone, as: :time_zone, prompt: t('.timezone')

  .form-actions
    = f.button :submit

app/views/channels/edit.html.haml
- title t('.title')

%p.nav
  - if can? :index, Channel
    = link_to t('back'), channels_path, class: 'index'
  - if can? :show, @channel
    = link_to t('show'), @channel, class: 'show'

= render 'form', channel: @channel

app/views/channels/index.html.haml
- title t('.title')

- if can? :new, Channel
  %p.nav= link_to t('.new_channel'), new_channel_path, class: 'new'

- if @channels.limit(1).size > 0
  - if @grid
    = grid @grid do |g|
      - g.column name: Channel.human_attribute_name(:logo),
        class: 'logo center' do |channel|
        - image_tag channel.logo, alt: channel.name rescue nil
      - g.column name: Channel.human_attribute_name(:name),
        class: 'name', attribute: 'name' do |channel|
        - channel.name
      - g.column name: Channel.human_attribute_name(:language),
        class: 'language', attribute: 'language',
            custom_filter: locales_for_select do |channel|
        - channel.language
      - g.column name: Channel.human_attribute_name(:home_url),
        class: 'home_url', attribute: 'home_url' do |channel|
        - link_to channel.home_url, channel.home_url, target: 'blank'
      - g.column name: Channel.human_attribute_name(:timezone),
          custom_filter: ActiveSupport::TimeZone.all.map{|tz| [tz.to_s, tz.name]},
          attribute: 'timezone' do |channel|
        - ActiveSupport::TimeZone.new(channel.timezone.to_s).to_s
      - g.column do |channel|
        - if can? :show, channel
          - link_to t('show'), channel, class: 'show'
      - g.column do |channel|
        - if can? :edit, channel
          - link_to t('edit'), edit_channel_path(channel), class: 'edit'
      - g.column do |channel|
        - if can? :destroy, channel
          - link_to t('destroy'), channel,
            data: {confirm: t('.confirm', default: 'Are you sure?')},
            method: :delete, class: 'destroy'
  -else
    %table
      %thead
        %tr
          %th= Channel.human_attribute_name :logo
          %th= Channel.human_attribute_name :name
          %th= Channel.human_attribute_name :language
          %th= Channel.human_attribute_name :home_url
          %th= Channel.human_attribute_name :timezone
          %th{colspan: 3}= t 'actions'

      %tbody
        - @channels.each do |channel|
          %tr{class: cycle(:odd, :even)}
            %td.logo= image_tag channel.logo, alt: channel.name
            %td.name= channel.name
            %td.language= channel.language
            %td.home_url= link_to channel.home_url, channel.home_url, target: 'blank'
            %td= ActiveSupport::TimeZone.new(channel.timezone.to_s).to_s
            %td.action
              - if can? :show, channel
                = link_to t('show'), channel, class: 'show'
            %td.action
              - if can? :edit, channel
                = link_to t('edit'), edit_channel_path(channel), class: 'edit'
            %td.action
              - if can? :destroy, channel
                = link_to t('destroy'), channel,
                  data: {confirm: t('.confirm', default: 'Are you sure?')},
                  method: :delete, class: 'destroy'
- else
  .empty
    = t '.empty'

app/views/channels/new.html.haml
- title t('.title')

- if can? :index, Channel
  %p.nav= link_to t('back'), channels_path, class: 'index'

= render 'form', channel: @channel

app/views/channels/show.html.haml
- title t '.title', name: @channel.name

%p.nav
  - if can? :index, Channel
    = link_to t('back'), channels_path, class: 'index'
  - if can? :edit, @channel
    = link_to t('edit'), edit_channel_path(@channel), class: 'edit'

%dl
  %dt= Channel.human_attribute_name :logo
  %dd.logo= image_tag @channel.logo, alt: @channel.name
  %dt= Channel.human_attribute_name :name
  %dd.name= @channel.name
  %dt= Channel.human_attribute_name :language
  %dd.language= @channel.language
  %dt= Channel.human_attribute_name :home_url
  %dd.home_url= link_to @channel.home_url, @channel.home_url, target: 'blank'
  - if can? :show_timezone, @channel
    %dt= User.human_attribute_name :timezone
    %dd= ActiveSupport::TimeZone.new(@channel.timezone.to_s).to_s